### ISSUE TITLE
Subfish crashes every time I click on the "Find" and closes immediately

### ISSUE THREAD

**Issue by Nokhodi** [SethRobinson/Subfish#2]
It crashes every time as soon as I click on the "Find" option and the program closes immediately، without giving any error message.

**Comment by SethRobinson** [comment]
Hi, thanks for the report.  

Anything weird/unique about your setup?  What version of Windows?

Alas, I'm unable to recreate this - if you click Find with no "Subtitle files" entries loaded (you can delete them all by highlighting them and pressing del), does it still crash?

If you only load one subtitle file, like https://www.youtube.com/watch?v=rfSlnz-fE3M for example, does it still crash?  (wondering if it's a specific subtitle that causes the problem)

I assumed you installed these two required files already: 

1. Install the .NET 5.0 Desktop Runtime. (Windows version is [here](https://dotnet.microsoft.com/download))

2. Install the WebView2 runtime ([Try here, look for x64 version probably](https://developer.microsoft.com/en-us/microsoft-edge/webview2/#download-section)).

**Comment by SethRobinson** [comment]
Thanks so much for the info.  I've installed this on a few more computers with roughly those specs but I wasn't able to reproduce the bug yet.  

Is your Windows region set to US/English?  If something else, please let me know and I will try it here.  A date format change might be cause string ops to fail for example.

**Comment by Nokhodi** [comment]
> Thanks so much for the info. I've installed this on a few more computers with roughly those specs but I wasn't able to reproduce the bug yet.
> 
> Is your Windows region set to US/English? If something else, please let me know and I will try it here. A date format change might be causing string ops to fail for example.

I set the region to "US/English" and now it seems to be working properly without crashing, it was set to "Iran/Persian (Iran)" before.

**Comment by SethRobinson** [comment]
Ahhh. Thanks.  I will fix this for the next version.  I always trip up on stuff like that.

**Comment by SethRobinson** [comment]
This has been fixed in the 1.08 release.
